/*
 * 4ALLPORTAL REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 * Contact: support@4allportal.net
 * Generated by: https://openapi-generator.tech
 */

use serde::{Serialize, Deserialize};


#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ApplicationManifest {
    #[serde(rename = "artifactId")]
    pub artifact_id: String,
    #[serde(rename = "artifactVersion", skip_serializing_if = "Option::is_none")]
    pub artifact_version: Option<String>,
    #[serde(rename = "postInstallUrl", skip_serializing_if = "Option::is_none")]
    pub post_install_url: Option<String>,
    #[serde(rename = "dependencies", skip_serializing_if = "Option::is_none")]
    pub dependencies: Option<Vec<crate::models::ApplicationArtifact>>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<::std::collections::HashMap<String, String>>,
    #[serde(rename = "flavor", skip_serializing_if = "Option::is_none")]
    pub flavor: Option<String>,
    #[serde(rename = "author", skip_serializing_if = "Option::is_none")]
    pub author: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<::std::collections::HashMap<String, String>>,
    #[serde(rename = "publishDate", skip_serializing_if = "Option::is_none")]
    pub publish_date: Option<String>,
    #[serde(rename = "installHook", skip_serializing_if = "Option::is_none")]
    pub install_hook: Option<String>,
    #[serde(rename = "preInstall", skip_serializing_if = "Option::is_none")]
    pub pre_install: Option<Box<crate::models::PreInstall>>,
    #[serde(rename = "infoUrl", skip_serializing_if = "Option::is_none")]
    pub info_url: Option<String>,
    #[serde(rename = "error", skip_serializing_if = "Option::is_none")]
    pub error: Option<Box<crate::models::ErrorResponseItem>>,
}

impl ApplicationManifest {
    pub fn new(artifact_id: String) -> ApplicationManifest {
        ApplicationManifest {
            artifact_id,
            artifact_version: None,
            post_install_url: None,
            dependencies: None,
            name: None,
            flavor: None,
            author: None,
            description: None,
            publish_date: None,
            install_hook: None,
            pre_install: None,
            info_url: None,
            error: None,
        }
    }
}


