/*
 * 4ALLPORTAL REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 * Contact: support@4allportal.net
 * Generated by: https://openapi-generator.tech
 */

use serde::{Serialize, Deserialize};


#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ChangePasswordRequest {
    #[serde(rename = "oldPassword", skip_serializing_if = "Option::is_none")]
    pub old_password: Option<String>,
    #[serde(rename = "newPassword", skip_serializing_if = "Option::is_none")]
    pub new_password: Option<String>,
}

impl ChangePasswordRequest {
    pub fn new() -> ChangePasswordRequest {
        ChangePasswordRequest {
            old_password: None,
            new_password: None,
        }
    }
}


