/*
 * 4ALLPORTAL REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 * Contact: support@4allportal.net
 * Generated by: https://openapi-generator.tech
 */

use serde::{Serialize, Deserialize};


#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DependencyCheck {
    #[serde(rename = "inbound", skip_serializing_if = "Option::is_none")]
    pub inbound: Option<Vec<crate::models::ApplicationWrapper>>,
    #[serde(rename = "outbound", skip_serializing_if = "Option::is_none")]
    pub outbound: Option<Vec<crate::models::ApplicationWrapper>>,
}

impl DependencyCheck {
    pub fn new() -> DependencyCheck {
        DependencyCheck {
            inbound: None,
            outbound: None,
        }
    }
}


