/*
 * 4ALLPORTAL REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 * Contact: support@4allportal.net
 * Generated by: https://openapi-generator.tech
 */

use serde::{Serialize, Deserialize};


#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GeneralConfigApi {
    #[serde(rename = "environments", skip_serializing_if = "Option::is_none")]
    pub environments: Option<::std::collections::HashMap<String, String>>,
    #[serde(rename = "valid", skip_serializing_if = "Option::is_none")]
    pub valid: Option<bool>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "externalUrl", skip_serializing_if = "Option::is_none")]
    pub external_url: Option<String>,
    #[serde(rename = "adminUserName", skip_serializing_if = "Option::is_none")]
    pub admin_user_name: Option<String>,
    #[serde(rename = "adminPassword", skip_serializing_if = "Option::is_none")]
    pub admin_password: Option<String>,
    #[serde(rename = "adminFirstname", skip_serializing_if = "Option::is_none")]
    pub admin_firstname: Option<String>,
    #[serde(rename = "adminLastname", skip_serializing_if = "Option::is_none")]
    pub admin_lastname: Option<String>,
    #[serde(rename = "adminEmail", skip_serializing_if = "Option::is_none")]
    pub admin_email: Option<String>,
    #[serde(rename = "defaultLanguage", skip_serializing_if = "Option::is_none")]
    pub default_language: Option<String>,
    #[serde(rename = "availableLanguages", skip_serializing_if = "Option::is_none")]
    pub available_languages: Option<Vec<String>>,
    #[serde(rename = "maintenance", skip_serializing_if = "Option::is_none")]
    pub maintenance: Option<bool>,
}

impl GeneralConfigApi {
    pub fn new() -> GeneralConfigApi {
        GeneralConfigApi {
            environments: None,
            valid: None,
            name: None,
            external_url: None,
            admin_user_name: None,
            admin_password: None,
            admin_firstname: None,
            admin_lastname: None,
            admin_email: None,
            default_language: None,
            available_languages: None,
            maintenance: None,
        }
    }
}


