/*
 * 4ALLPORTAL REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 * Contact: support@4allportal.net
 * Generated by: https://openapi-generator.tech
 */

use serde::{Serialize, Deserialize};


#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct InstallationRole {
    #[serde(rename = "modTime", skip_serializing_if = "Option::is_none")]
    pub mod_time: Option<i64>,
    #[serde(rename = "checksum", skip_serializing_if = "Option::is_none")]
    pub checksum: Option<String>,
    #[serde(rename = "identifier", skip_serializing_if = "Option::is_none")]
    pub identifier: Option<String>,
    #[serde(rename = "fullPath", skip_serializing_if = "Option::is_none")]
    pub full_path: Option<String>,
    #[serde(rename = "role", skip_serializing_if = "Option::is_none")]
    pub role: Option<crate::models::ModuleObject>,
    #[serde(rename = "role_accs", skip_serializing_if = "Option::is_none")]
    pub role_accs: Option<Vec<crate::models::InstallationRoleAccs>>,
    #[serde(rename = "features", skip_serializing_if = "Option::is_none")]
    pub features: Option<::std::collections::HashMap<String, Vec<crate::models::FeatureOrPresetAdminEntry>>>,
}

impl InstallationRole {
    pub fn new() -> InstallationRole {
        InstallationRole {
            mod_time: None,
            checksum: None,
            identifier: None,
            full_path: None,
            role: None,
            role_accs: None,
            features: None,
        }
    }
}


