/*
 * 4ALLPORTAL REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 * Contact: support@4allportal.net
 * Generated by: https://openapi-generator.tech
 */

use serde::{Serialize, Deserialize};


#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct MetricConfig {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "defaultUnit", skip_serializing_if = "Option::is_none")]
    pub default_unit: Option<String>,
}

impl MetricConfig {
    pub fn new() -> MetricConfig {
        MetricConfig {
            name: None,
            default_unit: None,
        }
    }
}


