/*
 * 4ALLPORTAL REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 * Contact: support@4allportal.net
 * Generated by: https://openapi-generator.tech
 */

use serde::{Serialize, Deserialize};


#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ObjectRenderer {
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub _type: Option<String>,
    #[serde(rename = "column_count", skip_serializing_if = "Option::is_none")]
    pub column_count: Option<i32>,
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
    #[serde(rename = "tooltip", skip_serializing_if = "Option::is_none")]
    pub tooltip: Option<String>,
    #[serde(rename = "label_placement", skip_serializing_if = "Option::is_none")]
    pub label_placement: Option<String>,
    #[serde(rename = "show_clear_buttons", skip_serializing_if = "Option::is_none")]
    pub show_clear_buttons: Option<bool>,
    #[serde(rename = "show_action_button", skip_serializing_if = "Option::is_none")]
    pub show_action_button: Option<bool>,
    #[serde(rename = "show_clear_button", skip_serializing_if = "Option::is_none")]
    pub show_clear_button: Option<bool>,
    #[serde(rename = "action_button_placement", skip_serializing_if = "Option::is_none")]
    pub action_button_placement: Option<String>,
    #[serde(rename = "group_renderer", skip_serializing_if = "Option::is_none")]
    pub group_renderer: Option<Vec<crate::models::GroupRenderer>>,
    #[serde(rename = "hidden_fields", skip_serializing_if = "Option::is_none")]
    pub hidden_fields: Option<Vec<crate::models::DataField>>,
    #[serde(rename = "search_attributes", skip_serializing_if = "Option::is_none")]
    pub search_attributes: Option<Box<crate::models::SearchAttributes>>,
    #[serde(rename = "default_sort_field", skip_serializing_if = "Option::is_none")]
    pub default_sort_field: Option<String>,
    #[serde(rename = "default_sort_order", skip_serializing_if = "Option::is_none")]
    pub default_sort_order: Option<DefaultSortOrder>,
}

impl ObjectRenderer {
    pub fn new() -> ObjectRenderer {
        ObjectRenderer {
            _type: None,
            column_count: None,
            label: None,
            tooltip: None,
            label_placement: None,
            show_clear_buttons: None,
            show_action_button: None,
            show_clear_button: None,
            action_button_placement: None,
            group_renderer: None,
            hidden_fields: None,
            search_attributes: None,
            default_sort_field: None,
            default_sort_order: None,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DefaultSortOrder {
    #[serde(rename = "NONE")]
    NONE,
    #[serde(rename = "ASC")]
    ASC,
    #[serde(rename = "DESC")]
    DESC,
}

impl Default for DefaultSortOrder {
    fn default() -> DefaultSortOrder {
        Self::NONE
    }
}

