/*
 * 4ALLPORTAL REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 * Contact: support@4allportal.net
 * Generated by: https://openapi-generator.tech
 */

use serde::{Serialize, Deserialize};


#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct OperationsRunRequestBody {
    #[serde(rename = "parameter", skip_serializing_if = "Option::is_none")]
    pub parameter: Option<::std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "ids")]
    pub ids: Vec<String>,
}

impl OperationsRunRequestBody {
    pub fn new(ids: Vec<String>) -> OperationsRunRequestBody {
        OperationsRunRequestBody {
            parameter: None,
            ids,
        }
    }
}


