/*
 * 4ALLPORTAL REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 * Contact: support@4allportal.net
 * Generated by: https://openapi-generator.tech
 */

use serde::{Serialize, Deserialize};


#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SnapInFiles {
    #[serde(rename = "filekey", skip_serializing_if = "Option::is_none")]
    pub filekey: Option<String>,
    #[serde(rename = "exists", skip_serializing_if = "Option::is_none")]
    pub exists: Option<bool>,
}

impl SnapInFiles {
    pub fn new() -> SnapInFiles {
        SnapInFiles {
            filekey: None,
            exists: None,
        }
    }
}


