/*
 * 4ALLPORTAL REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 * Contact: support@4allportal.net
 * Generated by: https://openapi-generator.tech
 */

use serde::{Serialize, Deserialize};


#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ValidationRule {
    #[serde(rename = "regexp", skip_serializing_if = "Option::is_none")]
    pub regexp: Option<String>,
    #[serde(rename = "regexp_fail_label", skip_serializing_if = "Option::is_none")]
    pub regexp_fail_label: Option<String>,
    #[serde(rename = "min", skip_serializing_if = "Option::is_none")]
    pub min: Option<f64>,
    #[serde(rename = "max", skip_serializing_if = "Option::is_none")]
    pub max: Option<f64>,
}

impl ValidationRule {
    pub fn new() -> ValidationRule {
        ValidationRule {
            regexp: None,
            regexp_fail_label: None,
            min: None,
            max: None,
        }
    }
}


