/*
 * 4ALLPORTAL REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 * Contact: support@4allportal.net
 * Generated by: https://openapi-generator.tech
 */

use serde::{Serialize, Deserialize};


#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ValueOptionGroup {
    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
    pub key: Option<Box<crate::models::JsonNullableString>>,
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<Box<crate::models::JsonNullableString>>,
    #[serde(rename = "info", skip_serializing_if = "Option::is_none")]
    pub info: Option<Box<crate::models::JsonNullableString>>,
    #[serde(rename = "items", skip_serializing_if = "Option::is_none")]
    pub items: Option<Vec<crate::models::ValueOptionItem>>,
}

impl ValueOptionGroup {
    pub fn new() -> ValueOptionGroup {
        ValueOptionGroup {
            key: None,
            label: None,
            info: None,
            items: None,
        }
    }
}


