/*
 * 4ALLPORTAL REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 * Contact: support@4allportal.net
 * Generated by: https://openapi-generator.tech
 */

use serde::{Serialize, Deserialize};


#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ValueOption {
    #[serde(rename = "sort", skip_serializing_if = "Option::is_none")]
    pub sort: Option<bool>,
    #[serde(rename = "groups", skip_serializing_if = "Option::is_none")]
    pub groups: Option<Vec<crate::models::ValueOptionGroup>>,
}

impl ValueOption {
    pub fn new() -> ValueOption {
        ValueOption {
            sort: None,
            groups: None,
        }
    }
}


