/*
 * 4ALLPORTAL REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 * Contact: support@4allportal.net
 * Generated by: https://openapi-generator.tech
 */

use serde::{Serialize, Deserialize};


#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ViewDeliveryConfig {
    #[serde(rename = "view", skip_serializing_if = "Option::is_none")]
    pub view: Option<String>,
    #[serde(rename = "visible", skip_serializing_if = "Option::is_none")]
    pub visible: Option<bool>,
}

impl ViewDeliveryConfig {
    pub fn new() -> ViewDeliveryConfig {
        ViewDeliveryConfig {
            view: None,
            visible: None,
        }
    }
}


