/*
 * 4ALLPORTAL REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 * Contact: support@4allportal.net
 * Generated by: https://openapi-generator.tech
 */

use serde::{Serialize, Deserialize};


#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct XmlDefaultValue {
    #[serde(rename = "generateDefault", skip_serializing_if = "Option::is_none")]
    pub generate_default: Option<bool>,
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
}

impl XmlDefaultValue {
    pub fn new() -> XmlDefaultValue {
        XmlDefaultValue {
            generate_default: None,
            value: None,
        }
    }
}


